#define PORT     8080 
#define MAXLINE 101 
#define MAXFILENUM 50
#define MAXPORTSIZE 4
#define MAXIPSIZE 15
#define MAXNAMESIZE 79
#define ERROR_404 "NOT FOUND"
#define ERROR_400 "BAD REQUEST"
#define ERROR_406 "DUPLICATE FILE"
#define ERROR_500 "INERNAL SERVER ERROR"
#define ERROR_512 "TOO MANY OWNERS"


